[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm cache clean --force", "npm ci --include=dev"]

[phases.build]
cmds = ["npm run build", "npm run db:push"]

[start]
cmd = "npm run start"
