[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cacheDirectories = []
cmds = ["npm install --include=dev"]

[phases.build]
cacheDirectories = []
cmds = ["npm run build", "npm run db:push"]

[start]
cmd = "npm run start"
