[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cacheDirectories = []
cmds = ["npm install --include=dev"]

[phases.build]
cacheDirectories = []
cmds = ["npm run build"]

[start]
cmd = "npm run db:push && npm run start"
